### ISSUE TITLE
BigDecimal Is Not Yet Implemented (NYI?)

### ISSUE THREAD

**Issue by opticyclic** [panchmp/sqlsheet#19]
If I select from a sheet and write using OpenCSV I get the following error:

```
Exception in thread "main" java.lang.IllegalStateException: NYI
    at com.googlecode.sqlsheet.stream.XlsStreamResultSet.nyi(XlsStreamResultSet.java:375)
    at com.googlecode.sqlsheet.stream.XlsStreamResultSet.getBigDecimal(XlsStreamResultSet.java:415)
    at au.com.bytecode.opencsv.ResultSetHelperService.getColumnValue(ResultSetHelperService.java:134)
    at au.com.bytecode.opencsv.ResultSetHelperService.getColumnValues(ResultSetHelperService.java:60)
    at au.com.bytecode.opencsv.CSVWriter.writeAll(CSVWriter.java:206)
    at Test.main(Test.java:27)
```

Sample code:

```
import au.com.bytecode.opencsv.CSVWriter;

import java.io.BufferedWriter;
import java.io.File;
import java.io.FileWriter;
import java.net.URL;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;

public class Test {
    public static void main(String[] args) throws Exception {
        Class.forName("com.googlecode.sqlsheet.Driver");

        URL url = Test.class.getResource("100.xls");
        File xls = new File(url.toURI());
        String connectionString = "jdbc:xls:file:" + xls.getAbsolutePath() + "?readStreaming=true";
        Connection connection = DriverManager.getConnection(connectionString);
        Statement statement = connection.createStatement();
        ResultSet resultSet = statement.executeQuery("select * from Sheet1");

        File file = new File("output.csv");
        FileWriter fileWriter = new FileWriter(file);
        BufferedWriter bufferedWriter = new BufferedWriter(fileWriter);
        CSVWriter csvWriter = new CSVWriter(bufferedWriter, CSVWriter.DEFAULT_SEPARATOR, CSVWriter.DEFAULT_QUOTE_CHARACTER, "\r\n");
        csvWriter.writeAll(resultSet, true);
        csvWriter.flush();
        csvWriter.close();
    }
}
```

**Comment by opticyclic** [comment]
See pull request https://github.com/panchmp/sqlsheet/pull/20

**Comment by klaushauschild1984** [comment]
Merged.
